// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9NbdMkkvKgUryQpqM3lctDYI93TTOYA8',
    appId: '1:209119526652:web:9371a0775f64ef4027e179',
    messagingSenderId: '209119526652',
    projectId: 'chat-app-8206b',
    authDomain: 'chat-app-8206b.firebaseapp.com',
    storageBucket: 'chat-app-8206b.appspot.com',
    measurementId: 'G-GNSVYEQFQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfryRBPttuhUZ5eB8zvE24tW5TYgQ1VBQ',
    appId: '1:209119526652:android:e36cd841ea13545d27e179',
    messagingSenderId: '209119526652',
    projectId: 'chat-app-8206b',
    storageBucket: 'chat-app-8206b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaobtpUf2DUuk-KXhwl8hPjsTY-uMeyhw',
    appId: '1:209119526652:ios:1c8097b7413fde1827e179',
    messagingSenderId: '209119526652',
    projectId: 'chat-app-8206b',
    storageBucket: 'chat-app-8206b.appspot.com',
    iosClientId: '209119526652-guujln3kba2dcskcgbjd1iluci3mhl6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaobtpUf2DUuk-KXhwl8hPjsTY-uMeyhw',
    appId: '1:209119526652:ios:1c8097b7413fde1827e179',
    messagingSenderId: '209119526652',
    projectId: 'chat-app-8206b',
    storageBucket: 'chat-app-8206b.appspot.com',
    iosClientId: '209119526652-guujln3kba2dcskcgbjd1iluci3mhl6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
